name: E2E

on:
  push:
    branches: ['master', 'features/e2e-tests']

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm i
      - run: npm i -g @azure/static-web-apps-cli
      - run: dotnet publish tests/e2e/Ignis.Tests.E2E.Website/Ignis.Tests.E2E.Website.csproj -c Release
      - run: swa deploy -d ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_E2E }} --env production
        working-directory: tests/e2e/Ignis.Tests.E2E.Website
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - run: dotnet build tests/e2e/Ignis.Tests.E2E/Ignis.Tests.E2E.csproj -c Release
      - run: pwsh tests/e2e/Ignis.Tests.E2E/bin/Release/net7.0/playwright.ps1 install --with-deps
      - run: dotnet test tests/e2e/Ignis.Tests.E2E/Ignis.Tests.E2E.csproj -c Release
