name: NPM Packages CD

on:
  push:
    tags: ['**']

jobs:
  Pack:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v3
        with:
          # https://github.com/actions/checkout/issues/701 https://github.com/actions/checkout/pull/579
          fetch-depth: 0
      - run: echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm i
        working-directory: packages/ignis.net/components
      - run: npm run build
        working-directory: packages/ignis.net/components
      - run: npm version $VERSION
        working-directory: packages/ignis.net/components
      - run: npm pack
        working-directory: packages/ignis.net/components
      - uses: actions/upload-artifact@v3
        with:
          name: NPM
          path: packages/ignis.net/components/*.tgz
  Publish:
    runs-on: ubuntu-latest
    needs: Pack
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org
      - uses: actions/download-artifact@v3
        with:
          name: NPM
          path: npm
      - run: find . -name '*.tgz' | xargs npm publish --access public
        working-directory: npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_KEY }}
