name: NuGet Packages CI

on:
  push:
    branches-ignore: [ 'main' ]
    tags-ignore: [ '**' ]
  pull_request:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm i
      - run: dotnet test
