name: Website (WebAssembly) CD

on:
  push:
    branches: ['website']
    tags: ['**']

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm i
      - run: npm i -g @azure/static-web-apps-cli
      - run: dotnet build website/Ignis.Website -c Release
      - run: dotnet doki g --allow-preview
      - run: |
          dotnet build tools/Ignis.Website.Generator -c Release
          dotnet tools/Ignis.Website.Generator/bin/Release/net8.0/Ignis.Website.Generator.dll
      - run: dotnet publish website/Ignis.Website.WebAssembly/Ignis.Website.WebAssembly.csproj -c Release
      - run: swa deploy -d ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} --env production
        working-directory: website/Ignis.Website.WebAssembly
